use std::collections::HashMap;
use std::sync::Arc;

use crate::{LanguageId, LanguagePlugin};

/// A lookup table from [`LanguageId`] to [`LanguagePlugin`].
///
/// [`SyntaxEngine`](crate::SyntaxEngine) owns the default registry (built-in
/// plugins like `mini_oxygen`); embedders can register additional plugins —
/// including ones generated by `sylven-dsl` — without touching this crate.
#[derive(Default)]
pub struct LanguageRegistry {
    plugins: HashMap<LanguageId, Arc<dyn LanguagePlugin>>,
}

impl LanguageRegistry {
    pub fn new() -> LanguageRegistry {
        LanguageRegistry::default()
    }

    /// Register `plugin`, replacing any existing plugin with the same id.
    pub fn register(&mut self, plugin: Arc<dyn LanguagePlugin>) {
        self.plugins.insert(plugin.id(), plugin);
    }

    pub fn get(&self, id: LanguageId) -> Option<&Arc<dyn LanguagePlugin>> {
        self.plugins.get(&id)
    }

    pub fn contains(&self, id: LanguageId) -> bool {
        self.plugins.contains_key(&id)
    }

    pub fn languages(&self) -> impl Iterator<Item = LanguageId> + '_ {
        self.plugins.keys().copied()
    }
}
